name: rider
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.2.3
  google_places_flutter: 2.1.0
  intl: ^0.20.2
  geolocator: ^13.0.3
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  google_sign_in: ^6.3.0
  url_launcher: ^6.3.1
  geocoding: ^2.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png