// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmNHkGnHwdQm3RRXlcmVLfRNTgDQuydMg',
    appId: '1:1082426468989:web:e607fae5f6d52f56325f14',
    messagingSenderId: '1082426468989',
    projectId: 'rider-chile-test',
    authDomain: 'rider-chile-test.firebaseapp.com',
    storageBucket: 'rider-chile-test.firebasestorage.app',
    measurementId: 'G-PDDQTKM8WC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrCYPW9AeZHn7KkgLC7Y2RdVPTTDp--bM',
    appId: '1:1082426468989:android:f504e0414da3e0fc325f14',
    messagingSenderId: '1082426468989',
    projectId: 'rider-chile-test',
    storageBucket: 'rider-chile-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5lV0Kx3FiP6GbM3L6laZkVqYS-HIo2Hw',
    appId: '1:1082426468989:ios:b3a402930fe7fd5a325f14',
    messagingSenderId: '1082426468989',
    projectId: 'rider-chile-test',
    storageBucket: 'rider-chile-test.firebasestorage.app',
    androidClientId: '1082426468989-84ou2rdu6vr3q3koj0vt53bhi8qvftqk.apps.googleusercontent.com',
    iosClientId: '1082426468989-jafjfp6vcn29a42tuun9rn5uc1euvcnm.apps.googleusercontent.com',
    iosBundleId: 'com.example.rider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5lV0Kx3FiP6GbM3L6laZkVqYS-HIo2Hw',
    appId: '1:1082426468989:ios:b3a402930fe7fd5a325f14',
    messagingSenderId: '1082426468989',
    projectId: 'rider-chile-test',
    storageBucket: 'rider-chile-test.firebasestorage.app',
    androidClientId: '1082426468989-84ou2rdu6vr3q3koj0vt53bhi8qvftqk.apps.googleusercontent.com',
    iosClientId: '1082426468989-jafjfp6vcn29a42tuun9rn5uc1euvcnm.apps.googleusercontent.com',
    iosBundleId: 'com.example.rider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmNHkGnHwdQm3RRXlcmVLfRNTgDQuydMg',
    appId: '1:1082426468989:web:a7259c49945234cb325f14',
    messagingSenderId: '1082426468989',
    projectId: 'rider-chile-test',
    authDomain: 'rider-chile-test.firebaseapp.com',
    storageBucket: 'rider-chile-test.firebasestorage.app',
    measurementId: 'G-BYZ17YYW7Y',
  );
}
